version: '3'

services:
  web:
    image: 'rubensluiz/django-docker-demo:latest'
    ports:
      - 8000:8000
    deploy:
      replicas: 10
    update_config:
        parallelism: 2
        delay: 10s
